
Seed: 12, Prompt: 1, Epoch: 1/50
Training:   0%|                                                           | 0/19 [00:00<?, ?batch/s]
Traceback (most recent call last):
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_PAES.py", line 234, in <module>
    main(args)
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_PAES.py", line 173, in main
    train_loss = train_model(model, train_loader, MSE_Loss, optimizer, device)
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/utils/evaluation.py", line 71, in train_model
    y_pred = model(x_train, linguistic_train, readability_train)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/models/paes.py", line 171, in forward
    essay_fea = torch.mean(essay_fea, dim=2, keepdim=False) # size: (batch_size, lstm_units)
UnboundLocalError: local variable 'essay_fea' referenced before assignment