2024-03-15 22:48:40,751 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-15 22:48:40,752 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Configure stats pid to 1380
2024-03-15 22:48:40,752 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Loading settings from /home/takumi/.config/wandb/settings
2024-03-15 22:48:40,753 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Loading settings from /mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/wandb/settings
2024-03-15 22:48:40,753 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-03-15 22:48:40,755 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-15 22:48:40,756 INFO    MainThread:1380 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_BERT.py', 'program_abspath': '/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_BERT.py', 'program': '/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_BERT.py'}
2024-03-15 22:48:40,758 INFO    MainThread:1380 [wandb_init.py:_log_setup():526] Logging user logs to /mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/wandb/run-20240315_224840-ggzep7p8/logs/debug.log
2024-03-15 22:48:40,759 INFO    MainThread:1380 [wandb_init.py:_log_setup():527] Logging internal logs to /mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/wandb/run-20240315_224840-ggzep7p8/logs/debug-internal.log
2024-03-15 22:48:40,759 INFO    MainThread:1380 [wandb_init.py:init():566] calling init triggers
2024-03-15 22:48:40,761 INFO    MainThread:1380 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'test_prompt_id': 1, 'seed': 12, 'attribute_name': 'score', 'output_dir': 'outputs/', 'experiment_name': 'DVRL_DomainAdaptation', 'dev_size': 60, 'data_dir': 'data/cross_prompt_attributes/', 'embedding_model': 'microsoft/deberta-v3-large', 'wandb_pjname': 'BERT-devonly-テスト', 'max_length': 512, 'batch_size': 32, 'epochs': 30, 'lr': 2e-05}
2024-03-15 22:48:40,763 INFO    MainThread:1380 [wandb_init.py:init():616] starting backend
2024-03-15 22:48:40,765 INFO    MainThread:1380 [wandb_init.py:init():620] setting up manager
2024-03-15 22:48:40,777 INFO    MainThread:1380 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-15 22:48:40,778 INFO    MainThread:1380 [wandb_init.py:init():628] backend started and connected
2024-03-15 22:48:40,782 INFO    MainThread:1380 [wandb_init.py:init():720] updated telemetry
2024-03-15 22:48:40,813 INFO    MainThread:1380 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-15 22:48:41,225 INFO    MainThread:1380 [wandb_run.py:_on_init():2262] communicating current version
2024-03-15 22:48:41,270 INFO    MainThread:1380 [wandb_run.py:_on_init():2271] got version response 
2024-03-15 22:48:41,270 INFO    MainThread:1380 [wandb_init.py:init():804] starting run threads in backend
2024-03-15 22:48:41,829 WARNING MainThread:1380 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/home/takumi/anaconda3/envs/torch/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-15 22:48:45,471 WARNING MsgRouterThr:1380 [router.py:message_loop():77] message_loop has been closed
